### ISSUE TITLE
[Svelte] npm configs missing in package.json

### ISSUE THREAD

**Issue by thorwebdev** [supabase/auth-ui#116]
Release scripts are failing ([e.g. this](https://github.com/supabase/auth-ui/actions/runs/4135858008/jobs/7148898574)) 

because https://github.com/supabase/auth-ui/blob/main/packages/svelte/package.json is missing 

```json
 "publishConfig": {
    "access": "public"
  },
```

And potentially a bunch of other stuff like main, module, files, types etc?

**Comment by silentworks** [comment]
Not a bug but intentional behavior, we still need to make some changes to the svelte package to match the design of the others hence why we haven't published a version as yet. Once ready we will add the correct config and publish it. Do note that this doesn't affect the publishing of other packages as shown in the screenshot.
 
![Screenshot_20230210_110923](https://user-images.githubusercontent.com/79497/218087829-307ac615-48e2-4040-b6fb-87f822f4aaa8.png)

**Comment by silentworks** [comment]
This is no longer an issue at all as the Svelte Auth UI has now been released.
